/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.sql;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for ElasticPoolEdition.
 */
public final class ElasticPoolEditions extends ExpandableStringEnum<ElasticPoolEditions> {
    /** Static value Basic for ElasticPoolEdition. */
    public static final ElasticPoolEditions BASIC = fromString("Basic");

    /** Static value Standard for ElasticPoolEdition. */
    public static final ElasticPoolEditions STANDARD = fromString("Standard");

    /** Static value Premium for ElasticPoolEdition. */
    public static final ElasticPoolEditions PREMIUM = fromString("Premium");

    /**
     * Creates or finds a ElasticPoolEdition from its string representation.
     * @param name a name to look for
     * @return the corresponding ElasticPoolEdition
     */
    @JsonCreator
    public static ElasticPoolEditions fromString(String name) {
        return fromString(name, ElasticPoolEditions.class);
    }

    /**
     * @return known ElasticPoolEdition values
     */
    public static Collection<ElasticPoolEditions> values() {
        return values(ElasticPoolEditions.class);
    }
}
