# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    npm install
    git config --global user.name "Azure-Fluent"
    git config --global user.email "azfluent@microsoft.com"
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: azuresdkpartnerdrops
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m -Dversion=1.27.3 -DdevVersion=1.27.4-SNAPSHOT'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'com.microsoft.azure:bundler-maven-plugin:auto'
