/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.recoveryservicessiterecovery;

import com.microsoft.azure.management.recoveryservicessiterecovery.implementation.UnplannedFailoverInputPropertiesInner;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Input definition for planned failover.
 */
public class UnplannedFailoverInput {
    /**
     * Planned failover input properties.
     */
    @JsonProperty(value = "properties")
    private UnplannedFailoverInputPropertiesInner properties;

    /**
     * Get the properties value.
     *
     * @return the properties value
     */
    public UnplannedFailoverInputPropertiesInner properties() {
        return this.properties;
    }

    /**
     * Set the properties value.
     *
     * @param properties the properties value to set
     * @return the UnplannedFailoverInput object itself.
     */
    public UnplannedFailoverInput withProperties(UnplannedFailoverInputPropertiesInner properties) {
        this.properties = properties;
        return this;
    }

}
