// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.management.network.model;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.JsonFlatten;
import com.azure.core.management.Resource;
import com.azure.management.network.BGPCommunity;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The BgpServiceCommunity model.
 */
@JsonFlatten
@Fluent
public class BgpServiceCommunityInner extends Resource {
    /*
     * The name of the bgp community. e.g. Skype.
     */
    @JsonProperty(value = "properties.serviceName")
    private String serviceName;

    /*
     * Get a list of bgp communities.
     */
    @JsonProperty(value = "properties.bgpCommunities")
    private List<BGPCommunity> bgpCommunities;

    /**
     * Get the serviceName property: The name of the bgp community. e.g. Skype.
     * 
     * @return the serviceName value.
     */
    public String getServiceName() {
        return this.serviceName;
    }

    /**
     * Set the serviceName property: The name of the bgp community. e.g. Skype.
     * 
     * @param serviceName the serviceName value to set.
     * @return the BgpServiceCommunityInner object itself.
     */
    public BgpServiceCommunityInner setServiceName(String serviceName) {
        this.serviceName = serviceName;
        return this;
    }

    /**
     * Get the bgpCommunities property: Get a list of bgp communities.
     * 
     * @return the bgpCommunities value.
     */
    public List<BGPCommunity> getBgpCommunities() {
        return this.bgpCommunities;
    }

    /**
     * Set the bgpCommunities property: Get a list of bgp communities.
     * 
     * @param bgpCommunities the bgpCommunities value to set.
     * @return the BgpServiceCommunityInner object itself.
     */
    public BgpServiceCommunityInner setBgpCommunities(List<BGPCommunity> bgpCommunities) {
        this.bgpCommunities = bgpCommunities;
        return this;
    }
}
