// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.management.network.model;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The EndpointServicesListResult model.
 */
@Fluent
public final class EndpointServicesListResultInner {
    /*
     * List of available endpoint services in a region.
     */
    @JsonProperty(value = "value")
    private List<EndpointServiceResultInner> value;

    /*
     * The URL to get the next set of results.
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Get the value property: List of available endpoint services in a region.
     * 
     * @return the value value.
     */
    public List<EndpointServiceResultInner> getValue() {
        return this.value;
    }

    /**
     * Set the value property: List of available endpoint services in a region.
     * 
     * @param value the value value to set.
     * @return the EndpointServicesListResultInner object itself.
     */
    public EndpointServicesListResultInner setValue(List<EndpointServiceResultInner> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: The URL to get the next set of results.
     * 
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: The URL to get the next set of results.
     * 
     * @param nextLink the nextLink value to set.
     * @return the EndpointServicesListResultInner object itself.
     */
    public EndpointServicesListResultInner setNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }
}
