/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.mediaservices;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for Flip.
 */
public enum Flip {
    /** Enum value None. */
    NONE("None"),

    /** Enum value Horizontal. */
    HORIZONTAL("Horizontal"),

    /** Enum value Vertical. */
    VERTICAL("Vertical");

    /** The actual serialized value for a Flip instance. */
    private String value;

    Flip(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a Flip instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed Flip object, or null if unable to parse.
     */
    @JsonCreator
    public static Flip fromString(String value) {
        Flip[] items = Flip.values();
        for (Flip item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
